trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  displayName: 'Terraform Init & Apply RG'
  inputs:
    azureSubscription: 'azure-sp-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform validate
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan